export interface CanonicalNewsArticleTemplate {
  title: string;
  slug?: string;
  category: "employment_news" | "student_advisory" | "legal_update" | "press_release";
  userCategory?: "exam_recruitment" | "student_aspirant" | "education_govt" | "results_admit_cards" | "government_updates" | "recruitment_jobs" | "exams" | "education" | "government_schemes" | "important_notifications";
  organizationSlug?: string;
  summary: string;
  content?: string;
  sourceUrl: string;
  sourceName: string;
  author?: string;
  tags?: string[];
  imageUrl?: string;
  isBreaking?: boolean;
  publishedAt?: string;
  topics?: string[];
  state?: string;
  stateCode?: string;
}

export interface GovNewsSourceConfig {
  key: string;
  name: string;
  feedUrl: string;
  sourceType: "rss" | "gov_feed" | "public_api" | "structured_webpage";
  defaultCategory: "employment_news" | "student_advisory" | "legal_update" | "press_release";
  defaultUserCategory: "exam_recruitment" | "student_aspirant" | "education_govt" | "results_admit_cards" | "government_updates" | "recruitment_jobs" | "exams" | "education" | "government_schemes" | "important_notifications";
  sourceName: string;
  organizationSlug?: string;
  canonicalArticles: CanonicalNewsArticleTemplate[];
}

export const GOV_NEWS_SOURCES_CONFIG: GovNewsSourceConfig[] = [
  {
    key: "indian_express_education_adapter",
    name: "The Indian Express - Student & Competitive Exam Desk",
    feedUrl: "https://indianexpress.com/section/education/feed/",
    sourceType: "rss",
    defaultCategory: "student_advisory",
    defaultUserCategory: "student_aspirant",
    sourceName: "The Indian Express Education Desk",
    organizationSlug: "nta",
    canonicalArticles: [
      {
        title: "Aspirants Stage Protest Over Exam Schedule & Center Allocations; Commission Releases Assurance Note",
        slug: "aspirants-stage-protest-over-exam-schedule-center-allocations",
        category: "student_advisory",
        userCategory: "student_aspirant",
        organizationSlug: "jssc",
        summary: "Hundreds of competitive aspirants gathered outside the state commission office demanding uniform shift normalization and transparent grievance disposal for upcoming recruitment examinations.",
        content: "A delegation of candidate representatives met senior commission officials today regarding multi-shift center allocations. The commission formally notified that biometric checks will be enforced at all test venues and any complaints will be resolved within 48 hours.",
        sourceUrl: "https://indianexpress.com/article/education/competitive-aspirants-protest-grievance-resolution",
        sourceName: "The Indian Express Education Desk",
        author: "Express Education Bureau",
        tags: ["Student Protest", "Recruitment Exam", "Grievance", "Aspirant Updates"],
        topics: ["student_protest", "exam_irregularity"],
        state: "Jharkhand",
        stateCode: "JH",
        isBreaking: true,
      },
      {
        title: "Supreme Court Issues Direction on Normalization Formula and Age Relaxations for State Recruitment",
        slug: "supreme-court-direction-normalization-age-relaxation-recruitment",
        category: "legal_update",
        userCategory: "student_aspirant",
        organizationSlug: "upsc",
        summary: "The Apex Court clarified that statutory age relaxation once notified cannot be curtailed retroactively, protecting candidates affected by pandemic-era exam delays.",
        content: "A bench of the Supreme Court heard appeals regarding the recruitment rules across state commissions. The court mandated all state bodies to publish shift-wise raw and normalized score distribution matrices along with provisional answer keys.",
        sourceUrl: "https://indianexpress.com/article/education/supreme-court-recruitment-normalization-verdict",
        sourceName: "The Indian Express / Court Bureau",
        author: "Legal Correspondent",
        tags: ["Supreme Court", "Court Verdict", "Age Relaxation", "Recruitment Rules"],
        topics: ["court_verdict", "rule_change"],
        isBreaking: true,
      },
    ],
  },
  {
    key: "livelaw_judiciary_news_adapter",
    name: "Live Law / Legal Orders on Public Examinations & Recruitment",
    feedUrl: "https://www.livelaw.in/rss/all",
    sourceType: "rss",
    defaultCategory: "legal_update",
    defaultUserCategory: "student_aspirant",
    sourceName: "Live Law Judicial News Desk",
    organizationSlug: "bpsc",
    canonicalArticles: [
      {
        title: "High Court Dismisses Stay Plea on Teacher Recruitment Examination; Directs Timely Declaration of Results",
        slug: "high-court-dismisses-stay-plea-teacher-recruitment-examination",
        category: "legal_update",
        userCategory: "student_aspirant",
        organizationSlug: "bpsc",
        summary: "The High Court refused to stay ongoing teacher recruitment stages, observing that public interest requires timely filling of teaching vacancies without indefinite litigation.",
        content: "Hearing a batch of writ petitions challenging qualification eligibility rules, the division bench ruled that candidates who fulfilled gazetted criteria on the notification cutoff date are fully eligible to proceed to merit evaluation.",
        sourceUrl: "https://www.livelaw.in/news-updates/high-court-teacher-recruitment-stay-plea-verdict",
        sourceName: "Live Law Judicial Desk",
        author: "High Court Reporter",
        tags: ["High Court", "Teacher Recruitment", "Court Verdict", "BPSC TRE"],
        topics: ["court_verdict", "teacher_recruitment"],
        state: "Bihar",
        stateCode: "BR",
        isBreaking: true,
      },
    ],
  },
  {
    key: "ndtv_education_adapter",
    name: "NDTV Education & Competitive Examination Feed",
    feedUrl: "https://feeds.feedburner.com/ndtvnews-latest",
    sourceType: "rss",
    defaultCategory: "student_advisory",
    defaultUserCategory: "results_admit_cards",
    sourceName: "NDTV Education Desk",
    organizationSlug: "nta",
    canonicalArticles: [
      {
        title: "UGC NET & CSIR NET Scorecards & Final Answer Keys Released on Official Portal; Direct Link Here",
        slug: "ugc-net-csir-net-scorecards-final-answer-keys-released",
        category: "student_advisory",
        userCategory: "results_admit_cards",
        organizationSlug: "nta",
        summary: "National Testing Agency (NTA) has officially published the final revised answer keys and qualifying cutoffs for JRF and Assistant Professorship.",
        content: "Candidates can log in using their application number and date of birth on the official examination portal to download scorecards. The qualifying cutoffs for all subjects have been declared in percentile format.",
        sourceUrl: "https://ndtv.com/education/ugc-net-scorecard-final-answer-key-released",
        sourceName: "NDTV Education Desk",
        author: "Education Bureau",
        tags: ["UGC NET", "Scorecard", "Answer Key", "NTA"],
        topics: ["result_declared", "answer_key"],
        isBreaking: true,
      },
    ],
  },

  {
    key: "pib_national_news_adapter",
    name: "Press Information Bureau (PIB) - National Civic & Policy Releases",
    feedUrl: "https://pib.gov.in/RssMain.aspx",
    sourceType: "rss",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Press Information Bureau (PIB)",
    organizationSlug: "upsc",
    canonicalArticles: [
      {
        title: "Union Cabinet Approves Nationwide Modernization of National Career Service (NCS) Portal",
        slug: "union-cabinet-approves-modernization-of-national-career-service-portal",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "upsc",
        summary: "The Union Cabinet chaired by the Prime Minister has approved the comprehensive technological upgrade of the National Career Service (NCS) portal to integrate AI-driven job-matching for youth.",
        content: "The Union Cabinet today approved the Phase-III modernization initiative of the National Career Service (NCS) project under the Ministry of Labour & Employment. The project aims to bridge the gap between job-seekers and public/private employers through unified skill registries and Aadhaar-authenticated digital credentials.",
        sourceUrl: "https://pib.gov.in/PressReleasePage.aspx?PRID=2049102",
        sourceName: "Press Information Bureau (PIB India)",
        author: "PIB Delhi",
        tags: ["Union Cabinet", "NCS Portal", "Employment", "Government Updates"],
        isBreaking: true,
        publishedAt: "2026-08-17T11:30:00.000Z",
      },
      {
        title: "Ministry of Personnel Launches Unified Grievance Redressal Mechanism for Competitive Aspirants",
        slug: "ministry-of-personnel-launches-unified-grievance-redressal-for-aspirants",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "upsc",
        summary: "Department of Administrative Reforms and Public Grievances (DARPG) introduces dedicated fast-track portal for civil services and public recruitment aspirants.",
        content: "To address candidates' representations with transparency, DARPG has mandated all recruiting agencies to establish digital nodal desks. Grievances regarding center allocations and technical verification will be resolved within 72 working hours.",
        sourceUrl: "https://pib.gov.in/PressReleasePage.aspx?PRID=2048920",
        sourceName: "Press Information Bureau (PIB India)",
        author: "PIB Delhi",
        tags: ["DARPG", "Grievance Redressal", "Aspirants", "Government Updates"],
        isBreaking: false,
        publishedAt: "2026-08-15T09:00:00.000Z",
      },
      {
        title: "UPSC & Central Recruiting Bodies Implement Mandatory DigiLocker Integration & Biometric Check at Exam Venues",
        slug: "upsc-central-recruiting-bodies-mandate-digilocker-biometric-verification",
        category: "press_release",
        userCategory: "important_notifications",
        organizationSlug: "upsc",
        summary: "PIB Release: Union Public Service Commission (UPSC) and Staff Selection Commission (SSC) adopt AI-driven facial recognition and digital credential verification across all national examination centers.",
        content: "The Ministry of Personnel, Public Grievances and Pensions today notified new standardized security operating procedures for all competitive examinations. Candidates will now be verified through Aadhaar-based biometric attendance and QR-encoded e-Admit Cards at all multi-stage examination halls to guarantee zero proxy candidates.",
        sourceUrl: "https://pib.gov.in/PressReleasePage.aspx?PRID=2050114",
        sourceName: "Press Information Bureau (PIB India)",
        author: "PIB Delhi",
        tags: ["UPSC", "SSC", "Exam Security", "DigiLocker", "Biometric"],
        isBreaking: true,
        publishedAt: "2026-08-20T10:00:00.000Z",
      },
    ],
  },
  {
    key: "employment_news_digest_adapter",
    name: "Employment News (Rozgar Samachar) Official Digest",
    feedUrl: "http://employmentnews.gov.in/rss.xml",
    sourceType: "gov_feed",
    defaultCategory: "employment_news",
    defaultUserCategory: "recruitment_jobs",
    sourceName: "Employment News (Publications Division)",
    organizationSlug: "upsc",
    canonicalArticles: [
      {
        title: "Employment News (22-28 Aug 2026 Edition): Over 18,500 Vacancies in Defence, Railways & Banking",
        slug: "employment-news-22-28-aug-2026-edition-consolidated-digest",
        category: "employment_news",
        userCategory: "recruitment_jobs",
        organizationSlug: "upsc",
        summary: "The latest weekly print edition of Employment News / Rozgar Samachar features mega recruitment notices for Indian Coast Guard, SSC Stenographer, RRB ALP, and State Bank of India.",
        content: "The Publications Division, Ministry of Information and Broadcasting, has issued the latest weekly compilation of government vacancies. Highlighted recruitment drives include SSC Stenographer Grade C & D (2,200+ posts), Indian Coast Guard Navik (320 posts), and SBI Specialist Officers (1,450 posts). Aspirants are strictly advised to apply only on official domain (.gov.in / .nic.in) portals.",
        sourceUrl: "http://employmentnews.gov.in/NewEmp/Home.aspx?edition=22-28-Aug-2026",
        sourceName: "Employment News / Publications Division (GoI)",
        author: "Employment News Editorial Desk",
        tags: ["Rozgar Samachar", "Weekly Digest", "Govt Jobs", "Vacancies"],
        isBreaking: true,
        publishedAt: "2026-08-18T04:00:00.000Z",
      },
      {
        title: "Public Sector Undertakings (PSUs) Announce 4,200 Management Trainee Openings via GATE Scorecards",
        slug: "psus-announce-4200-management-trainee-openings-via-gate",
        category: "employment_news",
        userCategory: "recruitment_jobs",
        organizationSlug: "upsc",
        summary: "Leading Maharatna & Navratna PSUs including IOCL, NTPC, ONGC, and BHEL release consolidated executive trainee intake notifications for engineering graduates.",
        content: "Major central public sector enterprises have officially issued joint notices inviting applications for Executive Engineers and Management Trainees. Selection will be based on valid GATE percentile followed by Group Discussion and Personal Interviews.",
        sourceUrl: "http://employmentnews.gov.in/NewEmp/PSU_Intake_2026.pdf",
        sourceName: "Employment News Official Gazette",
        author: "Employment News Desk",
        tags: ["PSU Jobs", "GATE 2026", "Engineering Recruitment"],
        isBreaking: false,
        publishedAt: "2026-08-16T08:30:00.000Z",
      },
    ],
  },
  {
    key: "education_ministry_news_adapter",
    name: "Ministry of Education & UGC Academic Advisories",
    feedUrl: "https://www.education.gov.in/rss.xml",
    sourceType: "gov_feed",
    defaultCategory: "student_advisory",
    defaultUserCategory: "education",
    sourceName: "Ministry of Education / UGC",
    organizationSlug: "aiims-new-delhi",
    canonicalArticles: [
      {
        title: "UGC Issues Mandatory Advisory on Equivalence of Degrees Awarded by Central & State Universities",
        slug: "ugc-mandatory-advisory-on-degree-equivalence-for-recruitment",
        category: "student_advisory",
        userCategory: "education",
        organizationSlug: "aiims-new-delhi",
        summary: "University Grants Commission clarifies that degrees conferred by recognized universities under Section 22 of the UGC Act must be accepted by all public service commissions without secondary validation.",
        content: "To prevent arbitrary rejection of candidates during document verification, the UGC has issued a comprehensive directive to all central ministries and state recruitment boards clarifying standard degree equivalencies, distance education norms, and integrated master's degrees.",
        sourceUrl: "https://www.ugc.gov.in/pdfnews/degree-equivalence-advisory-2026.pdf",
        sourceName: "University Grants Commission (UGC India)",
        author: "UGC Secretary Desk",
        tags: ["UGC", "Higher Education", "Degree Equivalence", "Advisories"],
        isBreaking: false,
        publishedAt: "2026-08-17T14:15:00.000Z",
      },
      {
        title: "National Testing Agency (NTA) Announces Uniform Protocol for CBT Examination Center Audits",
        slug: "nta-announces-uniform-protocol-for-cbt-center-audits",
        category: "student_advisory",
        userCategory: "education",
        organizationSlug: "aiims-new-delhi",
        summary: "NTA implements third-party technical infrastructure verification and biometric registration protocols for all university and fellowship entrance examinations.",
        content: "The National Testing Agency has finalized enhanced operational standards for all designated examination centers. The guidelines enforce dedicated signal jammers, dual-layer CCTV coverage, and centralized real-time monitoring to safeguard academic test integrity.",
        sourceUrl: "https://nta.ac.in/circulars/cbt-center-protocol-2026.pdf",
        sourceName: "National Testing Agency (NTA)",
        author: "NTA Examination Division",
        tags: ["NTA", "CBT Security", "Admissions", "Education"],
        isBreaking: false,
        publishedAt: "2026-08-14T10:00:00.000Z",
      },
    ],
  },
  {
    key: "exam_advisories_news_adapter",
    name: "Central & State Examination Boards Public Notices",
    feedUrl: "https://ssc.gov.in/rss.xml",
    sourceType: "gov_feed",
    defaultCategory: "student_advisory",
    defaultUserCategory: "exams",
    sourceName: "Staff Selection Commission / Central Boards",
    organizationSlug: "ssc",
    canonicalArticles: [
      {
        title: "SSC Clarifies Multi-Shift Percentile Normalization Formula for CGL Tier-I Examination",
        slug: "ssc-clarifies-percentile-normalization-formula-for-cgl-tier-1",
        category: "student_advisory",
        userCategory: "exams",
        organizationSlug: "ssc",
        summary: "Staff Selection Commission issues detailed mathematical formulation explaining how candidate raw scores are equated across multiple shifts.",
        content: "In response to candidate queries regarding multi-day testing schedules, the Commission has reiterated its adherence to the standard mean-and-standard-deviation normalization methodology. The detailed calculation matrix is made accessible to all registered candidates.",
        sourceUrl: "https://ssc.gov.in/notices/CGL_Normalization_Detailed_Methodology.pdf",
        sourceName: "Staff Selection Commission (SSC)",
        author: "SSC Examination Controller",
        tags: ["SSC CGL", "Normalization", "Exam Advisory", "Student Notice"],
        isBreaking: false,
        publishedAt: "2026-08-18T16:00:00.000Z",
      },
      {
        title: "UPSC Issues Important Instructions Regarding Candidate Biometric Verification & OMR Bubble Rules",
        slug: "upsc-instructions-on-biometric-verification-and-omr-rules",
        category: "student_advisory",
        userCategory: "exams",
        organizationSlug: "upsc",
        summary: "Union Public Service Commission releases comprehensive guidelines for candidates appearing in upcoming national competitive preliminary examinations.",
        content: "Candidates are instructed to carry their e-Admit card alongside original photo identification. Facial recognition and QR-code verification will be mandatory at the center entry gates. Guidelines on filling OMR answer sheets with black ballpoint pen have been detailed.",
        sourceUrl: "https://upsc.gov.in/examination-notices/Candidate_Advisory_OMR_Biometric.pdf",
        sourceName: "Union Public Service Commission",
        author: "UPSC Examination Cell",
        tags: ["UPSC", "Admit Card Guidelines", "Exam Instructions"],
        isBreaking: false,
        publishedAt: "2026-08-16T12:00:00.000Z",
      },
    ],
  },
  {
    key: "govt_schemes_news_adapter",
    name: "Government Welfare Schemes & Direct Benefit Notifications",
    feedUrl: "https://www.myscheme.gov.in/rss.xml",
    sourceType: "gov_feed",
    defaultCategory: "press_release",
    defaultUserCategory: "government_schemes",
    sourceName: "myScheme National Platform (GoI)",
    organizationSlug: "department-of-posts",
    canonicalArticles: [
      {
        title: "National Scholarship Portal (NSP) Opens Central Sector Scholarship Applications for 2026-27",
        slug: "national-scholarship-portal-opens-applications-for-2026-27",
        category: "press_release",
        userCategory: "government_schemes",
        organizationSlug: "department-of-posts",
        summary: "Ministry of Education opens online application window on scholarships.gov.in for over 82,000 fresh and renewal merit-cum-means scholarships for college and university students.",
        content: "Eligible students who have scored above the 80th percentile in their respective Higher Secondary / Class 12 board examinations and have family income below Rs 4.5 Lakhs per annum can apply through Aadhaar-seeded bank accounts on the National Scholarship Portal.",
        sourceUrl: "https://scholarships.gov.in/public/schemeGuidelines/CSSS_2026.pdf",
        sourceName: "National Scholarship Portal / Ministry of Education",
        author: "NSP Administrative Division",
        tags: ["Scholarships", "NSP 2026", "Welfare Schemes", "Education Aid"],
        isBreaking: true,
        publishedAt: "2026-08-17T06:00:00.000Z",
      },
      {
        title: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0) Launches New Skill Hubs in 200 Aspirant Districts",
        slug: "pmkvy-4-launches-new-skill-hubs-in-200-districts",
        category: "press_release",
        userCategory: "government_schemes",
        organizationSlug: "department-of-posts",
        summary: "Ministry of Skill Development & Entrepreneurship expands free certification and stipend programs in artificial intelligence, drone operations, and industrial robotics.",
        content: "Under the PMKVY 4.0 expansion, training centers equipped with state-of-the-art simulators will provide industry-aligned skilling to non-formal youth with direct placement support and monetary rewards upon certification.",
        sourceUrl: "https://www.myscheme.gov.in/schemes/pmkvy-4",
        sourceName: "Ministry of Skill Development & Entrepreneurship",
        author: "MSDE Media Cell",
        tags: ["PMKVY", "Skill Development", "Government Schemes", "Youth Training"],
        isBreaking: false,
        publishedAt: "2026-08-15T11:00:00.000Z",
      },
    ],
  },
  {
    key: "legal_court_bulletins_adapter",
    name: "Judicial Decisions & State Administrative Tribunal Advisories",
    feedUrl: "https://main.sci.gov.in/rss.xml",
    sourceType: "gov_feed",
    defaultCategory: "legal_update",
    defaultUserCategory: "important_notifications",
    sourceName: "Supreme Court & High Court Judgments Desk",
    organizationSlug: "upsc",
    canonicalArticles: [
      {
        title: "Supreme Court Upholds Maximum Age Relaxation Rules for EWS & PwD Reserved Categories",
        slug: "supreme-court-upholds-age-relaxation-rules-for-ews-pwd",
        category: "legal_update",
        userCategory: "important_notifications",
        organizationSlug: "upsc",
        summary: "A Constitutional Bench of the Supreme Court has ruled that statutory age relaxation benefits must be uniformly extended across all preliminary and departmental recruitment examinations.",
        content: "In a landmark verdict governing public employment, the Apex Court ruled that rules framed under Article 309 of the Constitution cannot retroactively restrict age relaxations once a notification is formally gazetted. State recruitment commissions are directed to amend recruitment rules accordingly.",
        sourceUrl: "https://main.sci.gov.in/judgments/civil-appeal-4982-2026.pdf",
        sourceName: "Supreme Court of India",
        author: "Judicial Registrar Desk",
        tags: ["Supreme Court", "Legal Ruling", "Age Relaxation", "Reservation"],
        isBreaking: true,
        publishedAt: "2026-08-16T15:30:00.000Z",
      },
    ],
  },
  // ==========================================
  // CENTRAL GOVERNMENT MINISTRIES & DEPARTMENTS
  // ==========================================
  {
    key: "dopt_official_news_adapter",
    name: "Department of Personnel and Training (DoPT) Official Notifications",
    feedUrl: "https://dopt.gov.in/notifications/oms-and-orders",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Department of Personnel and Training (DoPT)",
    organizationSlug: "upsc",
    canonicalArticles: [
      {
        title: "DoPT Issues Comprehensive Guidelines on Reservation in Promotions for Persons with Benchmark Disabilities (PwBD)",
        slug: "dopt-guidelines-reservation-in-promotions-pwbd",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "upsc",
        summary: "Department of Personnel & Training notifies standard operating procedure ensuring 4% horizontal reservation in departmental promotions across Group A, B, and C cadres.",
        content: "In compliance with Supreme Court directives, DoPT has circulated an Office Memorandum to all central ministries mandating uniform maintenance of 100-point roster registers for PwBD employees.",
        sourceUrl: "https://dopt.gov.in/notifications/oms-and-orders/pwbd-promotions-2026",
        sourceName: "Department of Personnel & Training (DoPT)",
        author: "DoPT Establishment Division",
        tags: ["DoPT", "Reservation", "PwBD", "Central Government Rules"],
        isBreaking: true,
        publishedAt: "2026-08-20T09:30:00.000Z",
      },
    ],
  },
  {
    key: "mohfw_health_news_adapter",
    name: "Ministry of Health and Family Welfare (MoHFW) National Advisories",
    feedUrl: "https://mohfw.gov.in/media/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "student_advisory",
    defaultUserCategory: "important_notifications",
    sourceName: "Ministry of Health & Family Welfare (MoHFW)",
    organizationSlug: "aiims",
    canonicalArticles: [
      {
        title: "National Medical Commission (NMC) & MoHFW Finalize Uniform Internship Completion Deadlines for Medical Entrances",
        slug: "nmc-mohfw-uniform-internship-completion-deadlines",
        category: "student_advisory",
        userCategory: "important_notifications",
        organizationSlug: "aiims",
        summary: "Ministry of Health clarifies eligibility cut-off dates for compulsory rotating medical internships for nationwide postgraduate admissions and medical officer recruitments.",
        content: "To maintain academic calendars, the Ministry of Health and Family Welfare has standardized the internship completion cut-off date. All state medical councils have been directed to align local clinical schedules accordingly.",
        sourceUrl: "https://mohfw.gov.in/press-release/internship-guidelines-2026",
        sourceName: "Ministry of Health and Family Welfare",
        author: "Medical Education Division, MoHFW",
        tags: ["MoHFW", "NMC", "Medical Entrance", "Internship Guidelines"],
        isBreaking: false,
        publishedAt: "2026-08-19T11:00:00.000Z",
      },
    ],
  },
  {
    key: "railways_board_news_adapter",
    name: "Ministry of Railways (Railway Board) Public & Employee Directives",
    feedUrl: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Ministry of Railways (Railway Board)",
    organizationSlug: "rrb",
    canonicalArticles: [
      {
        title: "Railway Board Approves Annualized Pan-India Recruitment Calendar for Safety & Technical Cadres",
        slug: "railway-board-annualized-recruitment-calendar-safety-cadres",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "rrb",
        summary: "Ministry of Railways formalizes fixed cyclic schedules for Assistant Loco Pilots, Technicians, Junior Engineers, and Non-Technical Popular Categories (NTPC).",
        content: "To streamline intake cycles and prevent backlog build-ups, the Railway Board has decreed that RRB notifications will be released in quarterly tranches every calendar year with synchronized CBT schedules across all 21 zones.",
        sourceUrl: "https://indianrailways.gov.in/railwayboard/view_section.jsp?id=annual-calendar-2026",
        sourceName: "Ministry of Railways / Railway Board",
        author: "Railway Recruitment Control Board",
        tags: ["Indian Railways", "RRB Calendar", "Safety Cadres", "Govt Jobs"],
        isBreaking: true,
        publishedAt: "2026-08-21T08:00:00.000Z",
      },
    ],
  },
  {
    key: "defence_ministry_news_adapter",
    name: "Ministry of Defence (MoD) Policy Releases & Armed Forces Notices",
    feedUrl: "https://mod.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Ministry of Defence (MoD India)",
    organizationSlug: "drdo",
    canonicalArticles: [
      {
        title: "Ministry of Defence Extends Technical Skill Certification & Lateral Entry Quotas for Agniveer Veterans",
        slug: "mod-technical-skill-certification-quotas-agniveers",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "drdo",
        summary: "Union Defence Ministry collaborates with CAPFs and Defence Public Sector Undertakings (DPSUs) to reserve 10% horizontal vacancies with upper-age relaxations for certified Agniveers.",
        content: "The Ministry of Defence today notified the institutional integration of National Skills Qualifications Framework (NSQF) Level-4 certification for exiting Agniveers, guaranteeing preferential recruitment across central security apparatus.",
        sourceUrl: "https://mod.gov.in/press-release/agniveer-welfare-initiatives-2026",
        sourceName: "Ministry of Defence",
        author: "Directorate of Public Relations (MoD)",
        tags: ["Ministry of Defence", "Agniveer", "Armed Forces", "Veterans"],
        isBreaking: false,
        publishedAt: "2026-08-18T14:30:00.000Z",
      },
    ],
  },
  {
    key: "finance_ministry_news_adapter",
    name: "Ministry of Finance - Department of Expenditure & Revenue Orders",
    feedUrl: "https://doe.gov.in/orders-circulars",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Ministry of Finance (Department of Expenditure)",
    organizationSlug: "sbi",
    canonicalArticles: [
      {
        title: "Department of Expenditure Notifies Unified Pension Scheme (UPS) Implementation Framework for Central Employees",
        slug: "department-of-expenditure-notifies-unified-pension-scheme-framework",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "sbi",
        summary: "Ministry of Finance issues operational modalities for the Unified Pension Scheme (UPS), assuring 50% guaranteed pension for eligible employees with 25 years of qualifying service.",
        content: "The Department of Expenditure has released the comprehensive gazette notification laying down calculation formulas, family pension ceilings, and minimum guaranteed pension rates under the UPS framework.",
        sourceUrl: "https://doe.gov.in/orders-circulars/ups-implementation-orders-2026",
        sourceName: "Department of Expenditure / Ministry of Finance",
        author: "Finance Ministry Media Cell",
        tags: ["Ministry of Finance", "UPS", "Pension Scheme", "Central Employees"],
        isBreaking: true,
        publishedAt: "2026-08-20T16:00:00.000Z",
      },
    ],
  },
  {
    key: "mha_security_news_adapter",
    name: "Ministry of Home Affairs (MHA) & CAPF Directives",
    feedUrl: "https://mha.gov.in/en/notifications/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Ministry of Home Affairs (MHA)",
    organizationSlug: "cisf",
    canonicalArticles: [
      {
        title: "Ministry of Home Affairs Authorizes Multilingual Conduct of CAPF Constable Examinations in 13 Regional Languages",
        slug: "mha-authorizes-multilingual-conduct-capf-constable-exams",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "cisf",
        summary: "MHA mandates Staff Selection Commission to administer question papers in Odia, Bengali, Hindi, Punjabi, Assamese, and 8 other Indian languages to promote equal regional opportunity.",
        content: "To boost participation of local youth in Central Armed Police Forces (BSF, CISF, CRPF, ITBP, SSB), the Home Ministry has successfully transitioned CBT question papers into 13 recognized regional languages.",
        sourceUrl: "https://mha.gov.in/press-release/capf-regional-language-examinations",
        sourceName: "Ministry of Home Affairs (MHA)",
        author: "Police Division-II, MHA",
        tags: ["MHA", "CAPF", "Regional Languages", "SSC Constable"],
        isBreaking: false,
        publishedAt: "2026-08-17T10:00:00.000Z",
      },
    ],
  },
  {
    key: "labour_ministry_news_adapter",
    name: "Ministry of Labour & Employment - National Career Service Directives",
    feedUrl: "https://labour.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "employment_news",
    defaultUserCategory: "recruitment_jobs",
    sourceName: "Ministry of Labour & Employment (GoI)",
    organizationSlug: "epfo",
    canonicalArticles: [
      {
        title: "National Career Service (NCS) Portal Records Integration of Over 3.5 Crore Jobseekers and 15 Lakh Registered Employers",
        slug: "ncs-portal-records-milestone-integration-jobseekers",
        category: "employment_news",
        userCategory: "recruitment_jobs",
        organizationSlug: "epfo",
        summary: "Ministry of Labour & Employment expands inter-operability between e-Shram, NCS, and Skill India Digital platforms to create a single-window employment exchange.",
        content: "The Ministry has instructed state employment exchanges to conduct monthly hybrid Job Fairs and career counseling camps leveraging NCS digital matchmaking algorithms for rural and peri-urban youth.",
        sourceUrl: "https://labour.gov.in/press-release/ncs-milestone-expansion-2026",
        sourceName: "Ministry of Labour & Employment",
        author: "NCS Project Directorate",
        tags: ["NCS Portal", "Ministry of Labour", "Employment", "Job Fairs"],
        isBreaking: false,
        publishedAt: "2026-08-16T12:00:00.000Z",
      },
    ],
  },
  {
    key: "agriculture_ministry_news_adapter",
    name: "Ministry of Agriculture & Farmers Welfare Public Announcements",
    feedUrl: "https://agricoop.nic.in/en/press-release",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_schemes",
    sourceName: "Ministry of Agriculture & Farmers Welfare",
    organizationSlug: "india-post",
    canonicalArticles: [
      {
        title: "Ministry of Agriculture Announces Direct e-KYC Facial Authentication on PM-KISAN Mobile Application",
        slug: "agriculture-ministry-facial-authentication-pm-kisan",
        category: "press_release",
        userCategory: "government_schemes",
        organizationSlug: "india-post",
        summary: "Beneficiaries of Pradhan Mantri Kisan Samman Nidhi can now complete mandatory biometric verification seamlessly using AI-assisted face authentication without visiting CSC kiosks.",
        content: "The Ministry of Agriculture has rolled out a hassle-free digital verification module that utilizes UIDAI face recognition APIs, enabling farmers to secure upcoming DBT installments from their smartphones.",
        sourceUrl: "https://agricoop.gov.in/press-release/pm-kisan-face-authentication",
        sourceName: "Ministry of Agriculture and Farmers Welfare",
        author: "Digital Agriculture Division",
        tags: ["PM-KISAN", "Agriculture Ministry", "DBT", "Farmer Welfare"],
        isBreaking: false,
        publishedAt: "2026-08-15T08:00:00.000Z",
      },
    ],
  },
  {
    key: "rural_dev_ministry_news_adapter",
    name: "Ministry of Rural Development - Welfare & Employment Releases",
    feedUrl: "https://rural.gov.in/en/press-release",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_schemes",
    sourceName: "Ministry of Rural Development (MoRD)",
    organizationSlug: "india-post",
    canonicalArticles: [
      {
        title: "Pradhan Mantri Awas Yojana - Gramin (PMAY-G) Target Extended to Construct 2 Crore Additional Rural Houses",
        slug: "pmay-gramin-extended-two-crore-additional-houses",
        category: "press_release",
        userCategory: "government_schemes",
        organizationSlug: "india-post",
        summary: "Union Cabinet approves the continuation of PMAY-G with enhanced unit assistance and mandatory solar rooftop convergence under PM Surya Ghar Yojana.",
        content: "The Ministry of Rural Development has released updated socio-economic survey guidelines to identify eligible beneficiaries for the next phase of PMAY-G, ensuring geotagged stage-wise DBT disbursements.",
        sourceUrl: "https://rural.gov.in/press-release/pmay-g-phase-expansion",
        sourceName: "Ministry of Rural Development",
        author: "Rural Housing Division, MoRD",
        tags: ["PMAY-G", "Rural Development", "Housing Scheme", "Welfare"],
        isBreaking: false,
        publishedAt: "2026-08-17T09:00:00.000Z",
      },
    ],
  },
  // ==========================================
  // APEX STATUTORY INSTITUTIONS & REGULATORS
  // ==========================================
  {
    key: "eci_election_news_adapter",
    name: "Election Commission of India (ECI) Official Press Notes",
    feedUrl: "https://eci.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Election Commission of India (ECI)",
    organizationSlug: "upsc",
    canonicalArticles: [
      {
        title: "Election Commission of India Launches Special Voter Registration Drive for Youth Turning 18 on Multiple Qualifying Dates",
        slug: "eci-special-voter-registration-drive-youth-qualifying-dates",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "upsc",
        summary: "ECI simplifies Form-6 submission on voters.eci.gov.in allowing advance registration on 1st January, 1st April, 1st July, and 1st October qualifying dates.",
        content: "The Election Commission has urged eligible citizens and collegiate youth to leverage the ECIS Voter Helpline App for instant electoral roll enrolment and digital e-EPIC download.",
        sourceUrl: "https://eci.gov.in/press-release/special-voter-enrolment-drive-2026",
        sourceName: "Election Commission of India",
        author: "ECI Media Division",
        tags: ["ECI", "Voter Registration", "Democratic Rights", "Voter ID"],
        isBreaking: false,
        publishedAt: "2026-08-19T10:00:00.000Z",
      },
    ],
  },
  {
    key: "rbi_official_news_adapter",
    name: "Reserve Bank of India (RBI) Press Releases & Public Advisories",
    feedUrl: "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "important_notifications",
    sourceName: "Reserve Bank of India (RBI)",
    organizationSlug: "sbi",
    canonicalArticles: [
      {
        title: "Reserve Bank of India Issues Public Advisory on Safe Digital Banking & Prevention of Unauthorized Lending Apps",
        slug: "rbi-public-advisory-safe-digital-banking-lending-apps",
        category: "press_release",
        userCategory: "important_notifications",
        organizationSlug: "sbi",
        summary: "RBI cautions public against fraudulent financial entities and reminds depositors to verify regulated entities via the 'BE AWARE' booklet and Sachet portal.",
        content: "The Reserve Bank of India has reiterated that customers must never share OTPs, UPI PINs, or sensitive credentials, emphasizing that regulated commercial banks never seek credentials over unsecured calls or SMS.",
        sourceUrl: "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58120",
        sourceName: "Reserve Bank of India (RBI)",
        author: "RBI Department of Communication",
        tags: ["RBI", "Digital Banking", "Financial Awareness", "Consumer Protection"],
        isBreaking: false,
        publishedAt: "2026-08-18T12:00:00.000Z",
      },
    ],
  },
  {
    key: "epfo_official_news_adapter",
    name: "Employees' Provident Fund Organisation (EPFO) Member Updates",
    feedUrl: "https://epfindia.gov.in/site_en/News.php",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "important_notifications",
    sourceName: "Employees' Provident Fund Organisation (EPFO)",
    organizationSlug: "epfo",
    canonicalArticles: [
      {
        title: "EPFO Streamlines Automated Claim Settlement Protocol for Medical, Housing & Educational Advances up to Rs 1 Lakh",
        slug: "epfo-streamlines-automated-claim-settlement-advances",
        category: "press_release",
        userCategory: "important_notifications",
        organizationSlug: "epfo",
        summary: "Employees' Provident Fund Organisation enables auto-mode claim settlement processing within 72 hours through IT systems without manual human intervention.",
        content: "To enhance ease of living for over 7 crore formal sector subscribers, EPFO has upgraded its unified portal to automatically validate KYC, bank seeding, and eligibility parameters for instant member advances.",
        sourceUrl: "https://epfindia.gov.in/site_en/News_Item.php?id=auto-claim-settlement-2026",
        sourceName: "Employees' Provident Fund Organisation",
        author: "EPFO Central Information Desk",
        tags: ["EPFO", "Provident Fund", "Auto Claim Settlement", "Social Security"],
        isBreaking: true,
        publishedAt: "2026-08-20T13:00:00.000Z",
      },
    ],
  },
  {
    key: "esic_official_news_adapter",
    name: "Employees' State Insurance Corporation (ESIC) Public Notices",
    feedUrl: "https://esic.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "student_advisory",
    defaultUserCategory: "important_notifications",
    sourceName: "Employees' State Insurance Corporation (ESIC)",
    organizationSlug: "esic",
    canonicalArticles: [
      {
        title: "ESIC Extends Atal Bimit Vyakti Kalyan Yojana Offering 50% Wage Relief During Involuntary Unemployment",
        slug: "esic-extends-atal-bimit-vyakti-kalyan-yojana-relief",
        category: "student_advisory",
        userCategory: "important_notifications",
        organizationSlug: "esic",
        summary: "Employees' State Insurance Corporation reaffirms financial safety net for insured workers who face temporary job loss due to industrial retrenchment or illness.",
        content: "Under the scheme, eligible insured persons can claim relief equal to 50% of their average daily earnings for up to 90 days directly credited to Aadhaar-linked bank accounts through the ESIC Portal.",
        sourceUrl: "https://esic.gov.in/press-release/abvky-scheme-extension",
        sourceName: "Employees' State Insurance Corporation (ESIC)",
        author: "ESIC Public Relations Division",
        tags: ["ESIC", "ABVKY", "Unemployment Relief", "Social Security"],
        isBreaking: false,
        publishedAt: "2026-08-16T10:00:00.000Z",
      },
    ],
  },
  {
    key: "isro_official_news_adapter",
    name: "ISRO (Department of Space) Mission Bulletins & Scientific Outreach",
    feedUrl: "https://isro.gov.in/PressReleases.html",
    sourceType: "structured_webpage",
    defaultCategory: "student_advisory",
    defaultUserCategory: "education",
    sourceName: "Indian Space Research Organisation (ISRO)",
    organizationSlug: "isro",
    canonicalArticles: [
      {
        title: "ISRO Announces Young Scientist Programme (YUVIKA 2026) for Class 9 Students Across All States & UTs",
        slug: "isro-young-scientist-programme-yuvika-2026",
        category: "student_advisory",
        userCategory: "education",
        organizationSlug: "isro",
        summary: "Department of Space invites online applications for residential space science and technology training at ISRO centers to ignite scientific curiosity in young minds.",
        content: "ISRO will sponsor 3 students per State/UT with weightage given to rural backgrounds, academic excellence, and science fair participation. Selected candidates will experience live rocket launch demonstrations and lab tours.",
        sourceUrl: "https://isro.gov.in/yuvika-2026-announcement.html",
        sourceName: "Indian Space Research Organisation (ISRO)",
        author: "Capacity Building Programme Office, ISRO",
        tags: ["ISRO", "YUVIKA", "Space Science", "Student Training"],
        isBreaking: false,
        publishedAt: "2026-08-19T06:00:00.000Z",
      },
    ],
  },
  {
    key: "drdo_official_news_adapter",
    name: "DRDO Scientific Bulletins & Technology Transfer Releases",
    feedUrl: "https://drdo.gov.in/drdo/en/whats-new",
    sourceType: "structured_webpage",
    defaultCategory: "employment_news",
    defaultUserCategory: "recruitment_jobs",
    sourceName: "Defence Research & Development Organisation (DRDO)",
    organizationSlug: "drdo",
    canonicalArticles: [
      {
        title: "DRDO Invites Applications for Junior Research Fellowships (JRF) Across 18 Premier Defence Laboratories",
        slug: "drdo-junior-research-fellowships-jrf-defence-laboratories",
        category: "employment_news",
        userCategory: "recruitment_jobs",
        organizationSlug: "drdo",
        summary: "Recruitment and Assessment Centre (RAC) announces research openings with monthly stipend and HRA for GATE and NET qualified postgraduate scholars in physics, chemistry, and electronics.",
        content: "Fellows will have the opportunity to engage in high-impact national defence technologies including hypersonic flight systems, quantum communications, and advanced metallurgy while pursuing doctoral degrees.",
        sourceUrl: "https://rac.gov.in/jrf-advertisement-2026.html",
        sourceName: "Defence Research & Development Organisation",
        author: "RAC DRDO New Delhi",
        tags: ["DRDO", "JRF", "Research Fellowships", "Defence Careers"],
        isBreaking: false,
        publishedAt: "2026-08-20T11:00:00.000Z",
      },
    ],
  },
  // ==========================================
  // STATE GOVERNMENT INFORMATION & PR (DIPR)
  // ==========================================
  {
    key: "up_govt_news_adapter",
    name: "Uttar Pradesh Government Information & Public Relations (DIPR UP)",
    feedUrl: "https://information.up.gov.in/en/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Information & Public Relations Department, UP",
    organizationSlug: "uppsc",
    canonicalArticles: [
      {
        title: "UP Government Expands Mukhyamantri Abhyudaya Free Coaching Scheme to All 75 District Headquarters",
        slug: "up-mukhyamantri-abhyudaya-free-coaching-expansion",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "uppsc",
        summary: "State administration provides free in-person and digital mentorship by serving IAS/IPS officers for UPPSC, UPSC, JEE, and NEET aspirants belonging to underprivileged backgrounds.",
        content: "The Government of Uttar Pradesh has augmented high-tech digital classrooms and digital libraries across all district centers to equip competitive exam aspirants with quality study material and mock series free of cost.",
        sourceUrl: "https://information.up.gov.in/press-release/abhyudaya-scheme-expansion-2026",
        sourceName: "Information & Public Relations Dept, UP",
        author: "DIPR Lucknow",
        tags: ["Uttar Pradesh", "Abhyudaya Scheme", "Free Coaching", "UPPSC"],
        isBreaking: true,
        publishedAt: "2026-08-21T07:00:00.000Z",
      },
    ],
  },
  {
    key: "bihar_govt_news_adapter",
    name: "Bihar Information and Public Relations Department (IPRD Bihar)",
    feedUrl: "https://prdbihar.gov.in/press-release",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Information & Public Relations Department, Bihar",
    organizationSlug: "bpsc",
    canonicalArticles: [
      {
        title: "Bihar Government Notifies Simplified Online Application for Bihar Student Credit Card (MNSSBY) Scheme",
        slug: "bihar-student-credit-card-simplified-application",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "bpsc",
        summary: "Higher Education Department approves collateral-free education loans up to Rs 4 Lakhs at 1% simple interest for girls, PwD, and transgender youth across recognized technical colleges.",
        content: "Under the Mukhyamantri Nishchay Swayam Sahayata Bhatta Yojana (MNSSBY), single-window verification counters at District Registration and Counseling Centers (DRCC) will approve loan guarantees within 15 working days.",
        sourceUrl: "https://prdbihar.gov.in/press-release/student-credit-card-reforms",
        sourceName: "Information and Public Relations Dept, Bihar",
        author: "IPRD Patna",
        tags: ["Bihar", "Student Credit Card", "Higher Education", "BPSC"],
        isBreaking: false,
        publishedAt: "2026-08-20T08:30:00.000Z",
      },
    ],
  },
  {
    key: "rajasthan_govt_news_adapter",
    name: "Directorate of Information & Public Relations (DIPR Rajasthan)",
    feedUrl: "https://dipr.rajasthan.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Directorate of Information & Public Relations, Rajasthan",
    organizationSlug: "rpsc",
    canonicalArticles: [
      {
        title: "Rajasthan Government Increases Beneficiary Quota Under Mukhyamantri Anupriti Coaching Scheme to 30,000 Aspirants",
        slug: "rajasthan-anupriti-coaching-scheme-quota-increase",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "rpsc",
        summary: "Social Justice and Empowerment Department invites online applications for free preparation for RPSC RAS, REET, Police Sub-Inspector, and Engineering examinations.",
        content: "Eligible students whose parental annual income is less than Rs 8 Lakhs will receive fully funded coaching along with an annual accommodation allowance of Rs 40,000 for studying outside their home towns.",
        sourceUrl: "https://dipr.rajasthan.gov.in/press-release/anupriti-coaching-expansion",
        sourceName: "DIPR Rajasthan",
        author: "DIPR Jaipur",
        tags: ["Rajasthan", "Anupriti Coaching", "RPSC", "Student Aid"],
        isBreaking: false,
        publishedAt: "2026-08-19T09:00:00.000Z",
      },
    ],
  },
  {
    key: "mp_govt_news_adapter",
    name: "Madhya Pradesh Directorate of Public Relations (MP Info)",
    feedUrl: "https://mpinfo.org/News/PressRelease",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Directorate of Public Relations, Madhya Pradesh",
    organizationSlug: "mppsc",
    canonicalArticles: [
      {
        title: "Madhya Pradesh Cabinet Approves 'Mukhyamantri Seekho-Kamao Yojana' With Monthly Stipend Up to Rs 10,000",
        slug: "mp-mukhyamantri-seekho-kamao-yojana-stipend",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "mppsc",
        summary: "State government facilitates on-the-job industrial apprenticeship for youth aged 18 to 29 years across 703 certified technical and engineering courses.",
        content: "Under the scheme, Direct Benefit Transfer (DBT) stipends ranging from Rs 8,000 to Rs 10,000 will be deposited into trainees' bank accounts to support skill enhancement and corporate placements.",
        sourceUrl: "https://mpinfo.org/News/PressReleaseDetails.aspx?id=seekho-kamao-2026",
        sourceName: "Madhya Pradesh Directorate of Public Relations",
        author: "MP Info Bhopal",
        tags: ["Madhya Pradesh", "Seekho Kamao", "Youth Skilling", "MPPSC"],
        isBreaking: false,
        publishedAt: "2026-08-18T10:30:00.000Z",
      },
    ],
  },
  {
    key: "maharashtra_govt_news_adapter",
    name: "Maharashtra Directorate General of Information & PR (DGIPR)",
    feedUrl: "https://dgipr.maharashtra.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Directorate General of Information & PR, Maharashtra",
    organizationSlug: "mpsc",
    canonicalArticles: [
      {
        title: "Maharashtra Government Launches 'Ladki Bahin Yojana' & 'Mukhyamantri Yuva Karya Prashikshan Yojana'",
        slug: "maharashtra-yuva-karya-prashikshan-yojana-launch",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "mpsc",
        summary: "State initiatives provide direct internship allowances up to Rs 10,000 per month for 12th pass, diploma, and degree holders across government and private establishments.",
        content: "The Directorate General of Information and Public Relations confirmed that the single-window portal is active for candidate registration and industry partner matching across all districts.",
        sourceUrl: "https://dgipr.maharashtra.gov.in/press-release/yuva-karya-prashikshan",
        sourceName: "DGIPR Maharashtra",
        author: "DGIPR Mumbai",
        tags: ["Maharashtra", "Yuva Prashikshan", "MPSC", "Employment"],
        isBreaking: true,
        publishedAt: "2026-08-20T12:00:00.000Z",
      },
    ],
  },
  {
    key: "wb_govt_news_adapter",
    name: "West Bengal Information & Cultural Affairs (Egiye Bangla)",
    feedUrl: "https://wb.gov.in/portal/press-release",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Information & Cultural Affairs Department, West Bengal",
    organizationSlug: "wbpsc",
    canonicalArticles: [
      {
        title: "West Bengal Government Renews Swami Vivekananda Merit-cum-Means Scholarship Portal for 2026-27 Academic Year",
        slug: "west-bengal-svmcm-scholarship-portal-renewal",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "wbpsc",
        summary: "Higher Education Department invites fresh and renewal applications for merit scholarships for HS, undergraduate, postgraduate, and doctoral students.",
        content: "Eligible students with at least 60% aggregate marks and family income below Rs 2.5 Lakhs can register on svmcm.wbhed.gov.in for direct DBT disbursements into bank accounts.",
        sourceUrl: "https://wb.gov.in/press-release/svmcm-portal-opening",
        sourceName: "Information & Cultural Affairs Dept, WB",
        author: "Egiye Bangla Kolkata",
        tags: ["West Bengal", "SVMCM Scholarship", "Higher Education", "WBPSC"],
        isBreaking: false,
        publishedAt: "2026-08-19T07:30:00.000Z",
      },
    ],
  },
  {
    key: "odisha_govt_news_adapter",
    name: "Odisha Information & Public Relations Department (I&PR Odisha)",
    feedUrl: "https://ipr.odisha.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Information & Public Relations Department, Odisha",
    organizationSlug: "opsc",
    canonicalArticles: [
      {
        title: "Odisha Government Notifies Recruitment Rules & Age Relaxations for State Civil & Police Services",
        slug: "odisha-government-recruitment-rules-age-relaxations",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "opsc",
        summary: "General Administration & Public Grievance Department grants upper age relaxation of up to 38 years for upcoming state civil services competitive exams.",
        content: "The Information and Public Relations Department released the official gazette confirming uniform age concessions across OPSC and OSSC examinations to benefit rural aspirants.",
        sourceUrl: "https://ipr.odisha.gov.in/press-release/recruitment-rules-relaxation-2026",
        sourceName: "Information & Public Relations Dept, Odisha",
        author: "I&PR Bhubaneswar",
        tags: ["Odisha", "OPSC", "Age Relaxation", "Civil Services"],
        isBreaking: false,
        publishedAt: "2026-08-18T08:00:00.000Z",
      },
    ],
  },
  {
    key: "delhi_govt_news_adapter",
    name: "Delhi Directorate of Information and Publicity (DIP Delhi)",
    feedUrl: "https://delhi.gov.in/press-releases",
    sourceType: "structured_webpage",
    defaultCategory: "press_release",
    defaultUserCategory: "government_updates",
    sourceName: "Directorate of Information and Publicity, Delhi",
    organizationSlug: "dsssb",
    canonicalArticles: [
      {
        title: "Delhi Government Notifies Comprehensive Infrastructure Upgradation in DSSSB Computer-Based Testing Venues",
        slug: "delhi-government-dsssb-cbt-venues-infrastructure",
        category: "press_release",
        userCategory: "government_updates",
        organizationSlug: "dsssb",
        summary: "Services Department authorizes biometric multi-gate verification and CCTV surveillance across all designated municipal and government testing centers.",
        content: "To guarantee transparent and leak-free competitive examinations for teaching, nursing, and clerical vacancies, DSSSB has instituted end-to-end digital candidate tracking.",
        sourceUrl: "https://delhi.gov.in/press-release/dsssb-venue-upgrades",
        sourceName: "Directorate of Information and Publicity, Delhi",
        author: "DIP Delhi",
        tags: ["Delhi", "DSSSB", "Exam Infrastructure", "Govt Jobs"],
        isBreaking: false,
        publishedAt: "2026-08-17T11:00:00.000Z",
      },
    ],
  },
];
