import { NavItem } from "@/types/common";

export const SITE_CONFIG = {
  name: "SuchnaSetu",
  tagline: "Official Public Information Aggregator",
  description: "A centralized, verified public portal aggregating and structuring official notifications from government bodies, commissions, and public authorities across India.",
  url: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  disclaimer: "SuchnaSetu is an independent public information aggregator. It is NOT a government entity, recruitment portal, or job agency. All listings cite direct official notification URLs.",
  links: {
    github: "https://github.com/suchnasetu",
    officialGazette: "https://egazette.gov.in",
  },
  contactEmail: "contact@suchnasetu.in",
} as const;

export const SYSTEM_MODULES = [
  {
    key: "jobs",
    title: "Government Jobs",
    shortTitle: "Govt Jobs",
    description: "Central, State & PSU recruitment notifications with post breakdown and eligibility.",
    href: "/jobs",
    icon: "Briefcase",
    status: "active",
    badge: "Available Now",
  },
  {
    key: "exams",
    title: "Government Exams",
    shortTitle: "Exams",
    description: "Examination calendars, test schedules, and qualification milestones.",
    href: "/exams",
    icon: "Calendar",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "results",
    title: "Results & Cutoffs",
    shortTitle: "Results",
    description: "Scorecards, merit lists, cutoff notices, and selection announcements.",
    href: "/results",
    icon: "Award",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "admit_cards",
    title: "Admit Cards",
    shortTitle: "Admit Cards",
    description: "Hall tickets, call letters, and test venue intimation releases.",
    href: "/admit-cards",
    icon: "FileText",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "schemes",
    title: "Government Schemes",
    shortTitle: "Schemes",
    description: "Central and state citizen welfare initiatives, grants, and subsidies.",
    href: "/schemes",
    icon: "ShieldCheck",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "scholarships",
    title: "Scholarships",
    shortTitle: "Scholarships",
    description: "Financial grants, merit fellowships, and higher education assistance.",
    href: "/scholarships",
    icon: "GraduationCap",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "tenders",
    title: "Public Tenders",
    shortTitle: "Tenders",
    description: "Official procurement notices, RFPs, and bidding deadlines.",
    href: "/tenders",
    icon: "FileSpreadsheet",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "circulars",
    title: "Circulars & Orders",
    shortTitle: "Circulars",
    description: "Official administrative memoranda, rules, and gazette notifications.",
    href: "/circulars",
    icon: "Layers",
    status: "upcoming",
    badge: "Coming Soon",
  },
  {
    key: "public_notices",
    title: "Public Notices",
    shortTitle: "Notices",
    description: "Statutory warnings, consumer advisories, and gazette releases.",
    href: "/public-notices",
    icon: "Bell",
    status: "upcoming",
    badge: "Coming Soon",
  },
] as const;

export const PUBLIC_NAV_ITEMS: NavItem[] = [
  { title: "Home", href: "/" },
  { title: "Government Jobs", href: "/jobs" },
  { title: "Employment News & Advisories", href: "/news" },
  { title: "Upcoming Modules", href: "/#modules" },
  { title: "Official Sources", href: "/#sources" },
];

export const ADMIN_NAV_ITEMS: NavItem[] = [
  { title: "Overview", href: "/admin", icon: "LayoutDashboard" },
  { title: "Government Jobs", href: "/admin/jobs", icon: "Briefcase" },
  { title: "Bulletins & News", href: "/admin/bulletins", icon: "Newspaper" },
  { title: "Organizations", href: "/admin/organizations", icon: "Building2" },
  { title: "Official Sources", href: "/admin/sources", icon: "Globe" },
  { title: "Audit Logs", href: "/admin/audit-logs", icon: "ScrollText" },
  { title: "System Settings", href: "/admin/settings", icon: "Settings" },
];
