export const BULLETIN_CATEGORIES = [
  {
    key: "government_updates",
    dbCategory: "press_release",
    label: "Government Updates",
    labelHindi: "सरकारी अपडेट",
    description: "Official union cabinet communiques, ministry press releases & civic policy updates",
    badge: "Govt Update",
  },
  {
    key: "recruitment_jobs",
    dbCategory: "employment_news",
    label: "Recruitment & Jobs",
    labelHindi: "भर्ती एवं रोजगार",
    description: "Weekly Rozgar Samachar digests & consolidated public sector vacancy circulars",
    badge: "Recruitment",
  },
  {
    key: "exams",
    dbCategory: "student_advisory",
    label: "Exams & Notifications",
    labelHindi: "परीक्षा सूचनाएं",
    description: "Exam schedules, shift normalization formulas, biometric guidelines & center advisories",
    badge: "Exams",
  },
  {
    key: "education",
    dbCategory: "student_advisory",
    label: "Education",
    labelHindi: "शिक्षा एवं प्रवेश",
    description: "UGC guidelines, university equivalence advisories, and admission circulars",
    badge: "Education",
  },
  {
    key: "government_schemes",
    dbCategory: "press_release",
    label: "Government Schemes",
    labelHindi: "सरकारी योजनाएं",
    description: "National welfare programs, scholarship portals, and direct beneficiary schemes",
    badge: "Schemes",
  },
  {
    key: "important_notifications",
    dbCategory: "student_advisory",
    label: "Important Notifications",
    labelHindi: "महत्वपूर्ण सूचनाएं",
    description: "Statutory student advisories, candidate representations, and urgency alerts",
    badge: "Notification",
  },
  {
    key: "legal_update",
    dbCategory: "legal_update",
    label: "Court & Legal Orders",
    labelHindi: "न्यायालय निर्णय",
    description: "Supreme Court and High Court judgments governing recruitment and reservation rules",
    badge: "Legal & Court",
  },
] as const;

export type BulletinCategoryKey = typeof BULLETIN_CATEGORIES[number]["key"] | "all" | "employment_news" | "student_advisory" | "press_release";
