import { NewsArticleDetailed } from "../types/article";

export const CANONICAL_NEWS_ARTICLES: NewsArticleDetailed[] = [
  {
    id: "news-art-1",
    slug: "union-cabinet-approves-modernization-of-national-career-service-portal",
    title: "Union Cabinet Approves Nationwide Modernization of National Career Service (NCS) Portal",
    summary: "The Union Cabinet chaired by the Prime Minister has approved the comprehensive technological upgrade of the National Career Service (NCS) portal to integrate AI-driven job-matching for youth.",
    content: "The Union Cabinet approved the Phase-III modernization initiative of the National Career Service (NCS) project under the Ministry of Labour & Employment. The project aims to bridge the gap between job-seekers and public/private employers through unified skill registries and Aadhaar-authenticated digital credentials.",
    source_name: "Press Information Bureau (PIB)",
    source_url: "https://pib.gov.in/PressReleasePage.aspx?PRID=2049102",
    canonical_url: "https://pib.gov.in/PressReleasePage.aspx?PRID=2049102",
    author: "PIB Delhi",
    category_slug: "governance",
    importance: "breaking",
    ai_status: "enriched",
    tags: ["Union Cabinet", "NCS Portal", "Governance", "Employment"],
    content_hash: "hash-ncs-portal-01",
    published_at: "2026-08-25T11:30:00.000Z",
    is_published: true,
    views_count: 3420,
    created_at: "2026-08-25T11:30:00.000Z",
    updated_at: "2026-08-25T11:30:00.000Z",
    translations: [
      {
        id: "tr-art-1-hi",
        article_id: "news-art-1",
        language_code: "hi",
        title: "केंद्रीय मंत्रिमंडल ने नेशनल करियर सर्विस (NCS) पोर्टल के देशव्यापी आधुनिकीकरण को दी मंजूरी",
        summary: "प्रधानमंत्री की अध्यक्षता में केंद्रीय मंत्रिमंडल ने युवाओं के लिए एआई-संचालित रोजगार मिलान को एकीकृत करने हेतु नेशनल करियर सर्विस (NCS) पोर्टल के व्यापक तकनीकी उन्नयन को मंजूरी दी है।",
        created_at: "2026-08-25T11:30:00.000Z",
        updated_at: "2026-08-25T11:30:00.000Z",
      },
    ],
  },
  {
    id: "news-art-2",
    slug: "isro-finalizes-launch-window-chandrayaan-4-sample-return-mission",
    title: "ISRO Finalizes Launch Window for Chandrayaan-4 Sample Return Mission",
    summary: "Indian Space Research Organisation announces key milestone preparations for the lunar sample return mission scheduled with multi-module docking architecture.",
    content: "ISRO Chairman confirmed that design configurations for Chandrayaan-4 have completed critical design review. The ambitious mission will collect lunar soil and rock samples from the southern polar region and return them to Earth.",
    source_name: "DD News National",
    source_url: "https://ddnews.gov.in/chandrayaan-4-launch-window-finalized",
    canonical_url: "https://ddnews.gov.in/chandrayaan-4-launch-window-finalized",
    author: "DD News Science Desk",
    category_slug: "technology",
    importance: "high",
    ai_status: "enriched",
    tags: ["ISRO", "Chandrayaan-4", "Space Technology", "Science"],
    content_hash: "hash-ch4-02",
    published_at: "2026-08-24T08:15:00.000Z",
    is_published: true,
    views_count: 4890,
    created_at: "2026-08-24T08:15:00.000Z",
    updated_at: "2026-08-24T08:15:00.000Z",
    translations: [
      {
        id: "tr-art-2-hi",
        article_id: "news-art-2",
        language_code: "hi",
        title: "इसरो ने चंद्रयान-4 सैंपल रिटर्न मिशन के लिए लॉन्च विंडो को दिया अंतिम रूप",
        summary: "भारतीय अंतरिक्ष अनुसंधान संगठन (ISRO) ने मल्टी-मॉड्यूल डॉकिंग तकनीक के साथ निर्धारित चंद्र नमूना वापसी मिशन के लिए महत्वपूर्ण मील के पत्थर की घोषणा की।",
        created_at: "2026-08-24T08:15:00.000Z",
        updated_at: "2026-08-24T08:15:00.000Z",
      },
    ],
  },
  {
    id: "news-art-3",
    slug: "ugc-mandatory-advisory-degree-equivalence-state-central-recruitment",
    title: "UGC Issues Mandatory Advisory on Equivalence of Degrees for All State & Central Recruitments",
    summary: "University Grants Commission directs all public recruiting commissions that degrees conferred by recognized universities under Section 22 must be accepted without secondary validation.",
    content: "To prevent arbitrary rejection of candidates during document verification, the UGC has issued a comprehensive directive to all central ministries and state recruitment boards clarifying standard degree equivalencies and distance education norms.",
    source_name: "The Hindu (National)",
    source_url: "https://www.thehindu.com/news/national/ugc-degree-equivalence-directive",
    canonical_url: "https://www.thehindu.com/news/national/ugc-degree-equivalence-directive",
    author: "National Bureau",
    category_slug: "education",
    importance: "high",
    ai_status: "enriched",
    tags: ["UGC", "Higher Education", "Degree Equivalence", "Advisories"],
    content_hash: "hash-ugc-03",
    published_at: "2026-08-23T14:20:00.000Z",
    is_published: true,
    views_count: 5120,
    created_at: "2026-08-23T14:20:00.000Z",
    updated_at: "2026-08-23T14:20:00.000Z",
    translations: [
      {
        id: "tr-art-3-hi",
        article_id: "news-art-3",
        language_code: "hi",
        title: "यूजीसी ने सभी केंद्रीय एवं राज्य भर्तियों हेतु डिग्री समकक्षता पर जारी की अनिवार्य एडवाइजरी",
        summary: "विश्वविद्यालय अनुदान आयोग (UGC) ने भर्ती आयोगों को निर्देश दिया है कि मान्यता प्राप्त विश्वविद्यालयों द्वारा प्रदान की गई डिग्रियों को बिना किसी अतिरिक्त सत्यापन के स्वीकार किया जाए।",
        created_at: "2026-08-23T14:20:00.000Z",
        updated_at: "2026-08-23T14:20:00.000Z",
      },
    ],
  },
  {
    id: "news-art-4",
    slug: "rbi-monetary-policy-keeps-repo-rate-steady-6-50",
    title: "Reserve Bank of India Keeps Repo Rate Steady at 6.50% Amid Robust GDP Growth",
    summary: "Monetary Policy Committee (MPC) unanimously decides to maintain the policy repo rate with a focus on sustainable disinflation and economic growth.",
    content: "The Reserve Bank of India Governor announced the bi-monthly monetary policy resolution, forecasting India's real GDP growth at 7.2% for the fiscal year while sustaining retail price stability.",
    source_name: "Press Information Bureau (PIB)",
    source_url: "https://pib.gov.in/PressReleasePage.aspx?PRID=2048991",
    canonical_url: "https://pib.gov.in/PressReleasePage.aspx?PRID=2048991",
    author: "PIB Mumbai",
    category_slug: "business",
    importance: "standard",
    ai_status: "enriched",
    tags: ["RBI", "Economy", "Repo Rate", "GDP Growth"],
    content_hash: "hash-rbi-04",
    published_at: "2026-08-22T06:45:00.000Z",
    is_published: true,
    views_count: 2190,
    created_at: "2026-08-22T06:45:00.000Z",
    updated_at: "2026-08-22T06:45:00.000Z",
    translations: [
      {
        id: "tr-art-4-hi",
        article_id: "news-art-4",
        language_code: "hi",
        title: "मजबूत जीडीपी वृद्धि के बीच भारतीय रिजर्व बैंक ने रेपो दर को 6.50% पर स्थिर रखा",
        summary: "मौद्रिक नीति समिति (MPC) ने सतत मुद्रास्फीति नियंत्रण और मजबूत आर्थिक विकास को समर्थन देने के लिए नीतिगत रेपो दर को अपरिवर्तित रखने का निर्णय लिया।",
        created_at: "2026-08-22T06:45:00.000Z",
        updated_at: "2026-08-22T06:45:00.000Z",
      },
    ],
  },
  {
    id: "news-art-5",
    slug: "nta-implements-dual-biometric-verification-exam-centers",
    title: "National Testing Agency (NTA) Implements Dual Biometric Verification at All Exam Centers",
    summary: "To reinforce security and prevent impersonation, NTA mandates real-time facial recognition and fingerprint registration at all national testing venues.",
    content: "The National Testing Agency has issued updated standard operating procedures for all computer-based tests and entrance exams across India, establishing secure digital auditing protocols.",
    source_name: "Indian Express Education",
    source_url: "https://indianexpress.com/article/education/nta-dual-biometric-protocol-2026",
    canonical_url: "https://indianexpress.com/article/education/nta-dual-biometric-protocol-2026",
    author: "Express News Service",
    category_slug: "education",
    importance: "standard",
    ai_status: "enriched",
    tags: ["NTA", "Exam Security", "CBT", "Biometric"],
    content_hash: "hash-nta-05",
    published_at: "2026-08-21T09:00:00.000Z",
    is_published: true,
    views_count: 6730,
    created_at: "2026-08-21T09:00:00.000Z",
    updated_at: "2026-08-21T09:00:00.000Z",
    translations: [
      {
        id: "tr-art-5-hi",
        article_id: "news-art-5",
        language_code: "hi",
        title: "राष्ट्रीय परीक्षा एजेंसी (NTA) ने सभी परीक्षा केंद्रों पर दोहरी बायोमेट्रिक सत्यापन प्रणाली लागू की",
        summary: "परीक्षाओं में पारदर्शिता सुनिश्चित करने और प्रतिरूपण रोकने के लिए एनटीए ने सभी राष्ट्रीय परीक्षा केंद्रों पर रियल-टाइम फेस रिकग्निशन अनिवार्य किया।",
        created_at: "2026-08-21T09:00:00.000Z",
        updated_at: "2026-08-21T09:00:00.000Z",
      },
    ],
  },
  {
    id: "news-art-6",
    slug: "health-ministry-expands-ayushman-bharat-digital-mission-district-hospitals",
    title: "Ministry of Health Expands Ayushman Bharat Digital Mission to 500 New District Hospitals",
    summary: "Health Ministry connects electronic health records and ABHA digital IDs across 500 additional district hospitals for paperless citizen healthcare.",
    content: "The Union Health Ministry announced the nationwide expansion of digital health infrastructure, allowing citizens to securely store diagnostic reports and medical history in verified digital health lockers.",
    source_name: "Press Information Bureau (PIB)",
    source_url: "https://pib.gov.in/PressReleasePage.aspx?PRID=2048700",
    canonical_url: "https://pib.gov.in/PressReleasePage.aspx?PRID=2048700",
    author: "PIB Delhi",
    category_slug: "health",
    importance: "standard",
    ai_status: "enriched",
    tags: ["Ayushman Bharat", "Healthcare", "Digital India", "Health"],
    content_hash: "hash-health-06",
    published_at: "2026-08-20T10:30:00.000Z",
    is_published: true,
    views_count: 1840,
    created_at: "2026-08-20T10:30:00.000Z",
    updated_at: "2026-08-20T10:30:00.000Z",
    translations: [
      {
        id: "tr-art-6-hi",
        article_id: "news-art-6",
        language_code: "hi",
        title: "स्वास्थ्य मंत्रालय ने आयुष्मान भारत डिजिटल मिशन का 500 नए जिला अस्पतालों में किया विस्तार",
        summary: "स्वास्थ्य मंत्रालय ने नागरिकों को पेपरलेस स्वास्थ्य सेवाएं प्रदान करने हेतु 500 अतिरिक्त जिला अस्पतालों में डिजिटल हेल्थ रिकॉर्ड और आभा आईडी को जोड़ा।",
        created_at: "2026-08-20T10:30:00.000Z",
        updated_at: "2026-08-20T10:30:00.000Z",
      },
    ],
  },
  {
    id: "news-art-7",
    slug: "national-sports-awards-2026-committee-announces-khel-ratna-nominations",
    title: "National Sports Awards Committee Announces Prestigious Khel Ratna & Arjuna Award Nominations",
    summary: "Ministry of Youth Affairs and Sports reveals official nominees for the annual National Sports Awards celebrating stellar international performances.",
    content: "The selection panel for the National Sports Awards 2026 has submitted its finalized list of awardees. The ceremony will be hosted at Rashtrapati Bhavan, honoring exemplary athletes across athletics, shooting, badminton, and hockey.",
    source_name: "DD News National",
    source_url: "https://ddnews.gov.in/sports/national-sports-awards-2026-nominations",
    canonical_url: "https://ddnews.gov.in/sports/national-sports-awards-2026-nominations",
    author: "DD Sports Desk",
    category_slug: "sports",
    importance: "standard",
    ai_status: "enriched",
    tags: ["National Sports Awards", "Khel Ratna", "Arjuna Award", "Sports"],
    content_hash: "hash-sports-07",
    published_at: "2026-08-19T12:00:00.000Z",
    is_published: true,
    views_count: 2950,
    created_at: "2026-08-19T12:00:00.000Z",
    updated_at: "2026-08-19T12:00:00.000Z",
    translations: [
      {
        id: "tr-art-7-hi",
        article_id: "news-art-7",
        language_code: "hi",
        title: "राष्ट्रीय खेल पुरस्कार समिति ने खेल रत्न एवं अर्जुन पुरस्कार नामांकनों की घोषणा की",
        summary: "युवा मामले और खेल मंत्रालय ने अंतरराष्ट्रीय स्तर पर उत्कृष्ट प्रदर्शन करने वाले खिलाड़ियों के लिए वार्षिक राष्ट्रीय खेल पुरस्कारों के आधिकारिक नामांकनों का खुलासा किया।",
        created_at: "2026-08-19T12:00:00.000Z",
        updated_at: "2026-08-19T12:00:00.000Z",
      },
    ],
  },
  {
    id: "news-art-8",
    slug: "up-cabinet-approves-youth-employment-incentive-scheme-2026",
    title: "Uttar Pradesh Cabinet Approves Mukhyamantri Yuva Udyami Vikas Abhiyan for 1 Lakh MSME Units",
    summary: "Uttar Pradesh government greenlights interest-free loans and technical mentorship for youth entrepreneurs aiming to establish manufacturing and service enterprises.",
    content: "The Uttar Pradesh Cabinet chaired by the Chief Minister has cleared the ambitious Mukhyamantri Yuva Udyami Vikas Abhiyan. The scheme guarantees interest-free financial assistance up to ₹5 lakh for trained youth passing out from ITIs, polytechnics, and skill centers, facilitating statewide grassroots industrialization.",
    source_name: "Information & Public Relations Dept, UP",
    source_url: "https://up.gov.in/news/yuva-udyami-scheme-2026",
    canonical_url: "https://up.gov.in/news/yuva-udyami-scheme-2026",
    author: "UP State Bureau",
    category_slug: "states",
    state_code: "UP",
    importance: "high",
    ai_status: "enriched",
    tags: ["Uttar Pradesh", "Youth Schemes", "MSME", "Employment", "UP Govt"],
    content_hash: "hash-up-08",
    published_at: "2026-08-26T09:30:00.000Z",
    is_published: true,
    views_count: 5820,
    created_at: "2026-08-26T09:30:00.000Z",
    updated_at: "2026-08-26T09:30:00.000Z",
    translations: [
      {
        id: "tr-art-8-hi",
        article_id: "news-art-8",
        language_code: "hi",
        title: "उत्तर प्रदेश कैबिनेट ने 1 लाख एमएसएमई इकाइयों हेतु मुख्यमंत्री युवा उद्यमी विकास अभियान को दी मंजूरी",
        summary: "उत्तर प्रदेश सरकार ने विनिर्माण और सेवा उद्यम स्थापित करने के इच्छुक युवा उद्यमियों के लिए ब्याज मुक्त ऋण और तकनीकी मार्गदर्शन को मंजूरी दी।",
        created_at: "2026-08-26T09:30:00.000Z",
        updated_at: "2026-08-26T09:30:00.000Z",
      },
    ],
  },
  {
    id: "news-art-9",
    slug: "bihar-education-department-announces-fourth-phase-teacher-counseling",
    title: "Bihar Education Department Announces Schedule for TRE Phase-4 School Teacher Document Verification",
    summary: "Bihar Public Service Commission (BPSC) and State Education Department finalize unified district counseling dates for primary, secondary, and senior secondary teacher appointees.",
    content: "The Bihar Education Department has officially released the detailed standard operating procedures for TRE Phase-4 teacher counseling across all 38 districts. Candidates will be authenticated through biometrics and digital verification to streamline appointments across government schools.",
    source_name: "Bihar State Information Centre",
    source_url: "https://state.bihar.gov.in/education/tre4-schedule",
    canonical_url: "https://state.bihar.gov.in/education/tre4-schedule",
    author: "Patna News Bureau",
    category_slug: "states",
    state_code: "BR",
    importance: "high",
    ai_status: "enriched",
    tags: ["Bihar", "BPSC TRE", "Education", "Teacher Recruitment", "Bihar Govt"],
    content_hash: "hash-br-09",
    published_at: "2026-08-26T08:00:00.000Z",
    is_published: true,
    views_count: 7420,
    created_at: "2026-08-26T08:00:00.000Z",
    updated_at: "2026-08-26T08:00:00.000Z",
    translations: [
      {
        id: "tr-art-9-hi",
        article_id: "news-art-9",
        language_code: "hi",
        title: "बिहार शिक्षा विभाग ने टीआरई चरण-4 विद्यालय शिक्षक दस्तावेज सत्यापन कार्यक्रम की घोषणा की",
        summary: "बिहार लोक सेवा आयोग (BPSC) और राज्य शिक्षा विभाग ने प्राथमिक, माध्यमिक और उच्च माध्यमिक शिक्षक अभ्यर्थियों हेतु एकीकृत जिला काउंसलिंग तिथियों को अंतिम रूप दिया।",
        created_at: "2026-08-26T08:00:00.000Z",
        updated_at: "2026-08-26T08:00:00.000Z",
      },
    ],
  },
  {
    id: "news-art-10",
    slug: "maharashtra-government-launches-ladki-bahin-yojana-digital-portal",
    title: "Maharashtra Government Launches Integrated Digital Portal for Mukhyamantri Majhi Ladki Bahin Yojana",
    summary: "Women & Child Development Department of Maharashtra deploys unified DBT portal for direct monthly benefit transfers reaching eligible women across all districts.",
    content: "The Government of Maharashtra has introduced the upgraded portal for Majhi Ladki Bahin Yojana, allowing women applicants to complete e-KYC and track monthly direct bank transfers seamlessly through mobile app and regional Seva Kendras.",
    source_name: "Maharashtra Directorate of General Information & PR (DGIPR)",
    source_url: "https://maharashtra.gov.in/news/ladki-bahin-portal-2026",
    canonical_url: "https://maharashtra.gov.in/news/ladki-bahin-portal-2026",
    author: "DGIPR Mumbai",
    category_slug: "states",
    state_code: "MH",
    importance: "high",
    ai_status: "enriched",
    tags: ["Maharashtra", "Women Welfare", "DBT", "Maha Govt"],
    content_hash: "hash-mh-10",
    published_at: "2026-08-25T14:00:00.000Z",
    is_published: true,
    views_count: 6110,
    created_at: "2026-08-25T14:00:00.000Z",
    updated_at: "2026-08-25T14:00:00.000Z",
    translations: [
      {
        id: "tr-art-10-hi",
        article_id: "news-art-10",
        language_code: "hi",
        title: "महाराष्ट्र सरकार ने मुख्यमंत्री माझी लाड़की बहिन योजना हेतु एकीकृत डिजिटल पोर्टल लॉन्च किया",
        summary: "महाराष्ट्र के महिला एवं बाल विकास विभाग ने सभी जिलों में पात्र महिलाओं तक मासिक प्रत्यक्ष लाभ अंतरण (DBT) पहुंचाने के लिए एकीकृत पोर्टल शुरू किया।",
        created_at: "2026-08-25T14:00:00.000Z",
        updated_at: "2026-08-25T14:00:00.000Z",
      },
    ],
  },
  {
    id: "news-art-11",
    slug: "delhi-transport-department-flags-off-500-electric-buses",
    title: "Delhi Government Flags Off 500 New Low-Floor AC Electric Buses to Expand Green Transit",
    summary: "Delhi Transport Corporation (DTC) adds 500 zero-emission electric buses equipped with GPS, panic buttons, and CCTV cameras for commuter safety.",
    content: "The Delhi Transport Department inducted 500 new electric buses into the public transit fleet today, bringing the total zero-emission fleet to over 2,500 buses. The rollout aims to significantly curb vehicular pollution and enhance last-mile urban connectivity across the National Capital Region.",
    source_name: "Delhi Government Information Department",
    source_url: "https://delhi.gov.in/news/electric-buses-rollout-2026",
    canonical_url: "https://delhi.gov.in/news/electric-buses-rollout-2026",
    author: "Delhi Desk",
    category_slug: "states",
    state_code: "DL",
    importance: "standard",
    ai_status: "enriched",
    tags: ["Delhi", "Electric Vehicles", "Green Transit", "DTC"],
    content_hash: "hash-dl-11",
    published_at: "2026-08-24T11:00:00.000Z",
    is_published: true,
    views_count: 4230,
    created_at: "2026-08-24T11:00:00.000Z",
    updated_at: "2026-08-24T11:00:00.000Z",
    translations: [
      {
        id: "tr-art-11-hi",
        article_id: "news-art-11",
        language_code: "hi",
        title: "दिल्ली सरकार ने हरित परिवहन को बढ़ावा देने के लिए 500 नई लो-फ्लोर एसी इलेक्ट्रिक बसों को हरी झंडी दिखाई",
        summary: "दिल्ली परिवहन निगम (DTC) ने यात्रियों की सुरक्षा हेतु जीपीएस, पैनिक बटन और सीसीटीवी कैमरों से लैस 500 शून्य-उत्सर्जन इलेक्ट्रिक बसों को बेड़े में शामिल किया।",
        created_at: "2026-08-24T11:00:00.000Z",
        updated_at: "2026-08-24T11:00:00.000Z",
      },
    ],
  },
  {
    id: "news-art-12",
    slug: "rajasthan-rpsc-calendar-announces-ras-exam-schedule",
    title: "Rajasthan Public Service Commission (RPSC) Releases 2026 Annual Competitive Examination Calendar",
    summary: "RPSC publishes official schedule for RAS/RTS Combined Competitive Exam, Assistant Professor, and School Lecturer examinations.",
    content: "The Rajasthan Public Service Commission (RPSC), Ajmer, has officially declared its annual recruitment calendar. The schedule outlines preliminary and mains examination dates for state administrative services, collegiate education cadres, and engineering departments across Rajasthan.",
    source_name: "RPSC Official Press Desk",
    source_url: "https://rpsc.rajasthan.gov.in/news/exam-calendar-2026",
    canonical_url: "https://rpsc.rajasthan.gov.in/news/exam-calendar-2026",
    author: "Jaipur News Bureau",
    category_slug: "states",
    state_code: "RJ",
    importance: "high",
    ai_status: "enriched",
    tags: ["Rajasthan", "RPSC", "RAS 2026", "Exam Calendar", "Rajasthan Govt"],
    content_hash: "hash-rj-12",
    published_at: "2026-08-23T10:00:00.000Z",
    is_published: true,
    views_count: 5310,
    created_at: "2026-08-23T10:00:00.000Z",
    updated_at: "2026-08-23T10:00:00.000Z",
    translations: [
      {
        id: "tr-art-12-hi",
        article_id: "news-art-12",
        language_code: "hi",
        title: "राजस्थान लोक सेवा आयोग (RPSC) ने 2026 वार्षिक प्रतियोगी परीक्षा कैलेंडर जारी किया",
        summary: "आरपीएससी ने आरएएस/आरटीएस संयुक्त प्रतियोगी परीक्षा, सहायक आचार्य और प्राध्यापक (स्कूल शिक्षा) परीक्षाओं हेतु आधिकारिक कार्यक्रम प्रकाशित किया।",
        created_at: "2026-08-23T10:00:00.000Z",
        updated_at: "2026-08-23T10:00:00.000Z",
      },
    ],
  },
];
