import { NewsSource } from "../types/source";

export const DEFAULT_NEWS_SOURCES: Omit<NewsSource, "id">[] = [
  // =========================================================================
  // 1. NATIONAL & GOVERNANCE NEWS SOURCES (DIRECT FEEDS)
  // =========================================================================
  {
    code: "the_hindu_national",
    name: "The Hindu National",
    website_url: "https://thehindu.com",
    feed_url: "https://www.thehindu.com/news/national/feeder/default.rss",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 20,
    failure_count: 0,
  },
  {
    code: "indian_express_india",
    name: "The Indian Express National",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/india/feed/",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 20,
    failure_count: 0,
  },
  {
    code: "pib_national",
    name: "Press Information Bureau (PIB)",
    website_url: "https://pib.gov.in",
    feed_url: "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1",
    source_type: "rss",
    default_category: "governance",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "ndtv_india",
    name: "NDTV India News",
    website_url: "https://ndtv.com",
    feed_url: "https://feeds.feedburner.com/ndtvnews-india-news",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },

  // =========================================================================
  // 2. EDUCATION, CAREERS & EXAMS (DIRECT FEEDS)
  // =========================================================================
  {
    code: "indian_express_edu",
    name: "Indian Express Education",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/education/feed/",
    source_type: "rss",
    default_category: "education",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 25,
    failure_count: 0,
  },
  {
    code: "the_hindu_education",
    name: "The Hindu Education & Career",
    website_url: "https://thehindu.com",
    feed_url: "https://www.thehindu.com/education/feeder/default.rss",
    source_type: "rss",
    default_category: "education",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },

  // =========================================================================
  // 3. BUSINESS, ECONOMY & TECHNOLOGY (DIRECT FEEDS)
  // =========================================================================
  {
    code: "the_hindu_business",
    name: "The Hindu Business & Economy",
    website_url: "https://thehindubusinessline.com",
    feed_url: "https://www.thehindubusinessline.com/economy/feeder/default.rss",
    source_type: "rss",
    default_category: "business",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 35,
    failure_count: 0,
  },
  {
    code: "indian_express_business",
    name: "Indian Express Business",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/business/feed/",
    source_type: "rss",
    default_category: "business",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 35,
    failure_count: 0,
  },
  {
    code: "indian_express_tech",
    name: "Indian Express Technology",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/technology/feed/",
    source_type: "rss",
    default_category: "technology",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 3,
    fetch_interval_minutes: 40,
    failure_count: 0,
  },

  // =========================================================================
  // 4. STATE & REGIONAL NEWS FEEDS (DIRECT REGIONAL FEEDS)
  // =========================================================================
  {
    code: "the_hindu_states",
    name: "The Hindu State News",
    website_url: "https://thehindu.com",
    feed_url: "https://www.thehindu.com/news/states/feeder/default.rss",
    source_type: "rss",
    default_category: "states",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 25,
    failure_count: 0,
  },
  {
    code: "up_state_lucknow",
    name: "Uttar Pradesh State Bureau (Lucknow)",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/lucknow/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "UP",
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "bihar_state_patna",
    name: "Bihar State Bureau (Patna)",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/patna/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "BR",
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "delhi_ncr_news",
    name: "Delhi NCR Civic & Governance",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/delhi/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "DL",
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "maharashtra_mumbai",
    name: "Maharashtra State Bureau (Mumbai)",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/mumbai/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "MH",
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "karnataka_bangalore",
    name: "Karnataka State Bureau (Bengaluru)",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/bangalore/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "KA",
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 35,
    failure_count: 0,
  },
  {
    code: "tamilnadu_chennai",
    name: "Tamil Nadu State Bureau (Chennai)",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/chennai/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "TN",
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 35,
    failure_count: 0,
  },
  {
    code: "west_bengal_kolkata",
    name: "West Bengal State Bureau (Kolkata)",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/kolkata/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "WB",
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 35,
    failure_count: 0,
  },
  {
    code: "punjab_haryana_chandigarh",
    name: "Punjab & Haryana Regional Bureau",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/cities/chandigarh/feed/",
    source_type: "rss",
    default_category: "states",
    state_code: "PB",
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 35,
    failure_count: 0,
  },
  {
    code: "google_news_india",
    name: "Google News India",
    website_url: "https://news.google.com",
    feed_url: "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 3,
    fetch_interval_minutes: 45,
    failure_count: 0,
  },
];
