import { NewsSource } from "../types/source";

export const DEFAULT_NEWS_SOURCES: Omit<NewsSource, "id">[] = [
  {
    code: "pib_national",
    name: "Press Information Bureau (PIB)",
    website_url: "https://pib.gov.in",
    feed_url: "https://pib.gov.in/RssMain.aspx",
    source_type: "rss",
    default_category: "governance",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 15,
    failure_count: 0,
  },
  {
    code: "dd_news",
    name: "DD News National",
    website_url: "https://ddnews.gov.in",
    feed_url: "https://ddnews.gov.in/rss-feeds",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 1,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "the_hindu_national",
    name: "The Hindu National",
    website_url: "https://thehindu.com",
    feed_url: "https://www.thehindu.com/news/national/feeder/default.rss",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "indian_express_edu",
    name: "Indian Express Education",
    website_url: "https://indianexpress.com",
    feed_url: "https://indianexpress.com/section/education/feed/",
    source_type: "rss",
    default_category: "education",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 2,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "ndtv_india",
    name: "NDTV India News",
    website_url: "https://ndtv.com",
    feed_url: "https://feeds.feedburner.com/ndtvnews-india-news",
    source_type: "rss",
    default_category: "india",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 3,
    fetch_interval_minutes: 30,
    failure_count: 0,
  },
  {
    code: "times_tech",
    name: "ET Tech & Digital India",
    website_url: "https://economictimes.indiatimes.com",
    feed_url: "https://economictimes.indiatimes.com/tech/rssfeeds/13357270.cms",
    source_type: "rss",
    default_category: "technology",
    state_code: null,
    country: "IN",
    is_enabled: true,
    priority: 3,
    fetch_interval_minutes: 45,
    failure_count: 0,
  },
];
